version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: userIsAbobus
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: adminIsAbobusToo
    ports:
     - 8081:8081
  app:
    build: 
      context: ../
      dockerfile: server/app/Dockerfile
    command: python3 app.py
    depends_on: 
     - mongo
    ports:
     - 5050:5050
    env_file:
      - .env
    container_name: server-app
